#!/usr/bin/env python3
"""
Compare LINC OFF vs ON report CSV outputs generated by focad_report.py.

Expected inputs (default in result_files/):
- fa_metrics_linc_off.csv
- fa_metrics_linc_on.csv
- fa_polarity_linc_off.csv
- fa_polarity_linc_on.csv

Outputs:
- fa_linc_comparison_summary.csv
- fa_linc_comparison_timeseries.csv
- fa_linc_comparison.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare LINC OFF vs ON FA outputs")
    parser.add_argument("--outdir", default="result_files", help="Folder containing tagged CSV outputs")
    parser.add_argument("--off-tag", default="linc_off", help="Tag suffix for OFF run")
    parser.add_argument("--on-tag", default="linc_on", help="Tag suffix for ON run")
    parser.add_argument("--show", action="store_true", help="Show plots interactively")
    return parser.parse_args()


def last20_mean(df: pd.DataFrame, col: str) -> float:
    if len(df) == 0:
        return float("nan")
    tail = df.iloc[int(0.8 * len(df)) :]
    return float(tail[col].mean())


def main() -> None:
    args = parse_args()
    outdir = Path(args.outdir)

    def resolve_csv(kind: str, tag: str) -> Path:
        candidates = [
            outdir / f"fa_{kind}_{tag}.csv",
            outdir / f"focad_{kind}_{tag}.csv",
        ]
        for path in candidates:
            if path.exists():
                return path
        raise FileNotFoundError(f"Could not find {kind} CSV for tag '{tag}'. Tried: {candidates}")

    met_off = pd.read_csv(resolve_csv("metrics", args.off_tag))
    met_on = pd.read_csv(resolve_csv("metrics", args.on_tag))
    pol_off = pd.read_csv(resolve_csv("polarity", args.off_tag))
    pol_on = pd.read_csv(resolve_csv("polarity", args.on_tag))

    n = min(len(met_off), len(met_on))
    met_off = met_off.iloc[:n].copy()
    met_on = met_on.iloc[:n].copy()

    cmp_ts = pd.DataFrame({
        "step": met_off["step"],
        "attached_ratio_off": met_off["attached_ratio"],
        "attached_ratio_on": met_on["attached_ratio"],
        "attached_ratio_delta_on_minus_off": met_on["attached_ratio"] - met_off["attached_ratio"],
        "mean_f_mag_off": met_off["mean_f_mag"],
        "mean_f_mag_on": met_on["mean_f_mag"],
        "mean_f_mag_delta_on_minus_off": met_on["mean_f_mag"] - met_off["mean_f_mag"],
    })
    cmp_ts.to_csv(outdir / "fa_linc_comparison_timeseries.csv", index=False)

    summary = {
        "off_attached_ratio_last20": last20_mean(met_off, "attached_ratio"),
        "on_attached_ratio_last20": last20_mean(met_on, "attached_ratio"),
        "delta_attached_ratio_on_minus_off_last20": last20_mean(met_on, "attached_ratio") - last20_mean(met_off, "attached_ratio"),
        "off_mean_f_mag_last20": last20_mean(met_off, "mean_f_mag"),
        "on_mean_f_mag_last20": last20_mean(met_on, "mean_f_mag"),
        "delta_mean_f_mag_on_minus_off_last20": last20_mean(met_on, "mean_f_mag") - last20_mean(met_off, "mean_f_mag"),
        "off_max_mean_f_mag": float(met_off["mean_f_mag"].max()),
        "on_max_mean_f_mag": float(met_on["mean_f_mag"].max()),
        "off_has_nan": bool(met_off[["attached_ratio", "mean_f_mag"]].isna().any().any()),
        "on_has_nan": bool(met_on[["attached_ratio", "mean_f_mag"]].isna().any().any()),
    }

    if len(pol_off) > 0 and len(pol_on) > 0:
        v_off = pol_off[(pol_off["front_count"] > 0) & (pol_off["rear_count"] > 0)]
        v_on = pol_on[(pol_on["front_count"] > 0) & (pol_on["rear_count"] > 0)]
        if len(v_off) > 0 and len(v_on) > 0:
            summary["off_front_minus_rear_attached_ratio_mean"] = float((v_off["front_attached_ratio"] - v_off["rear_attached_ratio"]).mean())
            summary["on_front_minus_rear_attached_ratio_mean"] = float((v_on["front_attached_ratio"] - v_on["rear_attached_ratio"]).mean())
            summary["delta_front_minus_rear_on_minus_off"] = summary["on_front_minus_rear_attached_ratio_mean"] - summary["off_front_minus_rear_attached_ratio_mean"]

    pd.DataFrame([summary]).to_csv(outdir / "fa_linc_comparison_summary.csv", index=False)

    fig, axes = plt.subplots(2, 1, figsize=(11, 8), sharex=True)

    ax = axes[0]
    ax.plot(cmp_ts["step"], cmp_ts["attached_ratio_off"], label="attached_ratio OFF", linewidth=2)
    ax.plot(cmp_ts["step"], cmp_ts["attached_ratio_on"], label="attached_ratio ON", linewidth=2)
    ax.plot(cmp_ts["step"], cmp_ts["attached_ratio_delta_on_minus_off"], label="delta (ON-OFF)", linestyle="--", linewidth=2)
    ax.set_ylabel("Attached ratio")
    ax.grid(alpha=0.25)
    ax.legend(loc="best")

    ax = axes[1]
    ax.plot(cmp_ts["step"], cmp_ts["mean_f_mag_off"], label="mean_f_mag OFF", linewidth=2)
    ax.plot(cmp_ts["step"], cmp_ts["mean_f_mag_on"], label="mean_f_mag ON", linewidth=2)
    ax.plot(cmp_ts["step"], cmp_ts["mean_f_mag_delta_on_minus_off"], label="delta (ON-OFF)", linestyle="--", linewidth=2)
    ax.set_xlabel("Step")
    ax.set_ylabel("Mean |F| (nN)")
    ax.grid(alpha=0.25)
    ax.legend(loc="best")

    fig.suptitle("LINC OFF vs ON Comparison")
    fig.tight_layout()
    fig.savefig(outdir / "fa_linc_comparison.png", dpi=180)

    if args.show:
        plt.show()
    else:
        plt.close("all")

    print(f"Saved: {outdir / 'fa_linc_comparison_timeseries.csv'}")
    print(f"Saved: {outdir / 'fa_linc_comparison_summary.csv'}")
    print(f"Saved: {outdir / 'fa_linc_comparison.png'}")


if __name__ == "__main__":
    main()
